[package]
name = "atlas-utils"
version.workspace = true
edition.workspace = true

[dependencies]
atlas-common = { workspace = true }
atlas-types = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
